services:
    rmbg2:
        ports:
            - 7866:7860
        image: rmbg2
        deploy:
          resources:
            reservations:
              devices:
                - driver: nvidia
                  count: all
                  capabilities: [gpu]